name: Deploy react app to Pages

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Unit tests
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: CI=false npm run build
      - name: Tar
        # github-pages artifact has to contain artifact.tar archive with app files in root
        run: cd build && tar -h -cvf ../artifact.tar --exclude=.git ./ && cd ..
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./artifact.tar
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
